//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo lo genera una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConviAppWeb {
    public partial class Gastos {
        protected global::System.Web.UI.WebControls.TextBox txtConcepto;
        protected global::System.Web.UI.WebControls.TextBox txtImporte;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.GridView gvGastos;
    }
}

