//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo lo genera una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConviAppWeb {
    public partial class Index {
        protected global::System.Web.UI.WebControls.Panel pnlPublico;
        protected global::System.Web.UI.WebControls.Panel pnlDashboard;
        protected global::System.Web.UI.WebControls.Label lblNumPisos;
        protected global::System.Web.UI.WebControls.Label lblTotalGastos;
        protected global::System.Web.UI.WebControls.Label lblNumTareas;
    }
}

