//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo lo genera una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConviAppWeb {
    public partial class Perfil {
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}

