//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo lo genera una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConviAppWeb {
    public partial class Pisos {
        protected global::System.Web.UI.WebControls.Button btnNuevo;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.TextBox txtDir;
        protected global::System.Web.UI.WebControls.TextBox txtCiudad;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.GridView gvPisos;
    }
}

